---
- hosts: all

  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      become: yes
      apt: update_cache=yes

    - name: Update all packages to the latest version
      become: yes
      apt: upgrade=dist

    - name: Install apt dependencies
      become: yes
      apt: name={{item}} state=installed
      with_items:
           # easy_install which will be sued to install pip
           - python-setuptools
           - libpython3.4-dev
           # not strictly necessary for the project as it runs on 3.4
           - libpython2.7-dev
           - tree
           - silversearcher-ag
           - python-imaging
           - libtiff5-dev
           - libjpeg8-dev
           - zlib1g-dev
           - libfreetype6-dev
           - liblcms2-dev
           - libwebp-dev
           - tcl8.6-dev
           - tk8.6-dev
           - python-tk
    - stat: path=/usr/local/bin/pip
      register: pip_installed

    - name: Install pip
      become: yes
      easy_install: name=pip state=latest
      when: pip_installed.stat.exists == False

    - name: Install latest core python libraries via pip
      become: yes
      pip: name={{item}} state=latest
      with_items:
        - setuptools
        - virtualenv

    - name: Manually create the initial virtualenv
      command: virtualenv /home/vagrant/venv -p python3.4 creates="/home/vagrant/venv"

    - name: Install pip production dependencies
      pip:
        requirements=~/workspace/buddy/requirements.txt
        virtualenv=/home/vagrant/venv

    - name: Install pip development dependencies
      pip:
        requirements=~/workspace/buddy/requirements_dev.txt
        virtualenv=/home/vagrant/venv
